name: ci
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ login do docker -u lukapagliarini }}
          password: ${{ a508e45d-2b21-4614-bbd1-b50ce83f730d }}
